/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.34
 * Generated at: 2021-01-25 14:11:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class books_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/decorator/admin/footer.jsp", Long.valueOf(1611562069039L));
    _jspx_dependants.put("/decorator/admin/navbar.jsp", Long.valueOf(1611560227548L));
    _jspx_dependants.put("/decorator/admin/header.jsp", Long.valueOf(1611560199423L));
    _jspx_dependants.put("/decorator/admin/slidebar.jsp", Long.valueOf(1611561227108L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<meta charset=\"ISO-8859-1\">\r\n");
      out.write("\t<title>Insert title here</title>\r\n");
      out.write("\t<link href=\"/template/style.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"/template/plugins/fontawesome-free/css/all.min.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"/template/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"/template/plugins/icheck-bootstrap/icheck-bootstrap.min.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"/template/plugins/jqvmap/jqvmap.min.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"/template/dist/css/adminlte.min.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"/template/plugins/overlayScrollbars/css/OverlayScrollbars.min.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"/template/plugins/daterangepicker/daterangepicker.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"/template/plugins/summernote/summernote-bs4.min.css\">\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"hold-transition sidebar-mini layout-fixed\">\r\n");
      out.write("\t<div class=\"wrapper\">\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t <!-- Navbar -->\r\n");
      out.write("\t    <nav class=\"main-header navbar navbar-expand navbar-white navbar-light\">\r\n");
      out.write("\t      <!-- Left navbar links -->\r\n");
      out.write("\t      <ul class=\"navbar-nav\">\r\n");
      out.write("\t        <li class=\"nav-item\">\r\n");
      out.write("\t          <a class=\"nav-link\" data-widget=\"pushmenu\" href=\"#\" role=\"button\"><i class=\"fas fa-bars\"></i></a>\r\n");
      out.write("\t        </li>\r\n");
      out.write("\t        <li class=\"nav-item d-none d-sm-inline-block\">\r\n");
      out.write("\t          <a href=\"index3.html\" class=\"nav-link\">Home</a>\r\n");
      out.write("\t        </li>\r\n");
      out.write("\t        <li class=\"nav-item d-none d-sm-inline-block\">\r\n");
      out.write("\t          <a href=\"#\" class=\"nav-link\">Contact</a>\r\n");
      out.write("\t        </li>\r\n");
      out.write("\t      </ul>\r\n");
      out.write("\t\r\n");
      out.write("\t      <!-- SEARCH FORM -->\r\n");
      out.write("\t      <form class=\"form-inline ml-3\">\r\n");
      out.write("\t        <div class=\"input-group input-group-sm\">\r\n");
      out.write("\t          <input class=\"form-control form-control-navbar\" type=\"search\" placeholder=\"Search\" aria-label=\"Search\">\r\n");
      out.write("\t          <div class=\"input-group-append\">\r\n");
      out.write("\t            <button class=\"btn btn-navbar\" type=\"submit\">\r\n");
      out.write("\t              <i class=\"fas fa-search\"></i>\r\n");
      out.write("\t            </button>\r\n");
      out.write("\t          </div>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t      </form>\r\n");
      out.write("\t\r\n");
      out.write("\t      <!-- Right navbar links -->\r\n");
      out.write("\t      <ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("\t        <!-- Messages Dropdown Menu -->\r\n");
      out.write("\t        <li class=\"nav-item dropdown\">\r\n");
      out.write("\t          <a class=\"nav-link\" data-toggle=\"dropdown\" href=\"#\">\r\n");
      out.write("\t            <i class=\"far fa-comments\"></i>\r\n");
      out.write("\t            <span class=\"badge badge-danger navbar-badge\">3</span>\r\n");
      out.write("\t          </a>\r\n");
      out.write("\t          <div class=\"dropdown-menu dropdown-menu-lg dropdown-menu-right\">\r\n");
      out.write("\t            <a href=\"#\" class=\"dropdown-item\">\r\n");
      out.write("\t              <!-- Message Start -->\r\n");
      out.write("\t              <div class=\"media\">\r\n");
      out.write("\t                <img src=\"dist/img/user1-128x128.jpg\" alt=\"User Avatar\" class=\"img-size-50 mr-3 img-circle\">\r\n");
      out.write("\t                <div class=\"media-body\">\r\n");
      out.write("\t                  <h3 class=\"dropdown-item-title\">\r\n");
      out.write("\t                    Brad Diesel\r\n");
      out.write("\t                    <span class=\"float-right text-sm text-danger\"><i class=\"fas fa-star\"></i></span>\r\n");
      out.write("\t                  </h3>\r\n");
      out.write("\t                  <p class=\"text-sm\">Call me whenever you can...</p>\r\n");
      out.write("\t                  <p class=\"text-sm text-muted\"><i class=\"far fa-clock mr-1\"></i> 4 Hours Ago</p>\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t              </div>\r\n");
      out.write("\t              <!-- Message End -->\r\n");
      out.write("\t            </a>\r\n");
      out.write("\t            <div class=\"dropdown-divider\"></div>\r\n");
      out.write("\t            <a href=\"#\" class=\"dropdown-item\">\r\n");
      out.write("\t              <!-- Message Start -->\r\n");
      out.write("\t              <div class=\"media\">\r\n");
      out.write("\t                <img src=\"dist/img/user8-128x128.jpg\" alt=\"User Avatar\" class=\"img-size-50 img-circle mr-3\">\r\n");
      out.write("\t                <div class=\"media-body\">\r\n");
      out.write("\t                  <h3 class=\"dropdown-item-title\">\r\n");
      out.write("\t                    John Pierce\r\n");
      out.write("\t                    <span class=\"float-right text-sm text-muted\"><i class=\"fas fa-star\"></i></span>\r\n");
      out.write("\t                  </h3>\r\n");
      out.write("\t                  <p class=\"text-sm\">I got your message bro</p>\r\n");
      out.write("\t                  <p class=\"text-sm text-muted\"><i class=\"far fa-clock mr-1\"></i> 4 Hours Ago</p>\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t              </div>\r\n");
      out.write("\t              <!-- Message End -->\r\n");
      out.write("\t            </a>\r\n");
      out.write("\t            <div class=\"dropdown-divider\"></div>\r\n");
      out.write("\t            <a href=\"#\" class=\"dropdown-item\">\r\n");
      out.write("\t              <!-- Message Start -->\r\n");
      out.write("\t              <div class=\"media\">\r\n");
      out.write("\t                <img src=\"dist/img/user3-128x128.jpg\" alt=\"User Avatar\" class=\"img-size-50 img-circle mr-3\">\r\n");
      out.write("\t                <div class=\"media-body\">\r\n");
      out.write("\t                  <h3 class=\"dropdown-item-title\">\r\n");
      out.write("\t                    Nora Silvester\r\n");
      out.write("\t                    <span class=\"float-right text-sm text-warning\"><i class=\"fas fa-star\"></i></span>\r\n");
      out.write("\t                  </h3>\r\n");
      out.write("\t                  <p class=\"text-sm\">The subject goes here</p>\r\n");
      out.write("\t                  <p class=\"text-sm text-muted\"><i class=\"far fa-clock mr-1\"></i> 4 Hours Ago</p>\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t              </div>\r\n");
      out.write("\t              <!-- Message End -->\r\n");
      out.write("\t            </a>\r\n");
      out.write("\t            <div class=\"dropdown-divider\"></div>\r\n");
      out.write("\t            <a href=\"#\" class=\"dropdown-item dropdown-footer\">See All Messages</a>\r\n");
      out.write("\t          </div>\r\n");
      out.write("\t        </li>\r\n");
      out.write("\t        <!-- Notifications Dropdown Menu -->\r\n");
      out.write("\t        <li class=\"nav-item dropdown\">\r\n");
      out.write("\t          <a class=\"nav-link\" data-toggle=\"dropdown\" href=\"#\">\r\n");
      out.write("\t            <i class=\"far fa-bell\"></i>\r\n");
      out.write("\t            <span class=\"badge badge-warning navbar-badge\">15</span>\r\n");
      out.write("\t          </a>\r\n");
      out.write("\t          <div class=\"dropdown-menu dropdown-menu-lg dropdown-menu-right\">\r\n");
      out.write("\t            <span class=\"dropdown-item dropdown-header\">15 Notifications</span>\r\n");
      out.write("\t            <div class=\"dropdown-divider\"></div>\r\n");
      out.write("\t            <a href=\"#\" class=\"dropdown-item\">\r\n");
      out.write("\t              <i class=\"fas fa-envelope mr-2\"></i> 4 new messages\r\n");
      out.write("\t              <span class=\"float-right text-muted text-sm\">3 mins</span>\r\n");
      out.write("\t            </a>\r\n");
      out.write("\t            <div class=\"dropdown-divider\"></div>\r\n");
      out.write("\t            <a href=\"#\" class=\"dropdown-item\">\r\n");
      out.write("\t              <i class=\"fas fa-users mr-2\"></i> 8 friend requests\r\n");
      out.write("\t              <span class=\"float-right text-muted text-sm\">12 hours</span>\r\n");
      out.write("\t            </a>\r\n");
      out.write("\t            <div class=\"dropdown-divider\"></div>\r\n");
      out.write("\t            <a href=\"#\" class=\"dropdown-item\">\r\n");
      out.write("\t              <i class=\"fas fa-file mr-2\"></i> 3 new reports\r\n");
      out.write("\t              <span class=\"float-right text-muted text-sm\">2 days</span>\r\n");
      out.write("\t            </a>\r\n");
      out.write("\t            <div class=\"dropdown-divider\"></div>\r\n");
      out.write("\t            <a href=\"#\" class=\"dropdown-item dropdown-footer\">See All Notifications</a>\r\n");
      out.write("\t          </div>\r\n");
      out.write("\t        </li>\r\n");
      out.write("\t        <li class=\"nav-item\">\r\n");
      out.write("\t          <a class=\"nav-link\" data-widget=\"fullscreen\" href=\"#\" role=\"button\">\r\n");
      out.write("\t            <i class=\"fas fa-expand-arrows-alt\"></i>\r\n");
      out.write("\t          </a>\r\n");
      out.write("\t        </li>\r\n");
      out.write("\t        <li class=\"nav-item\">\r\n");
      out.write("\t          <a class=\"nav-link\" data-widget=\"control-sidebar\" data-slide=\"true\" href=\"#\" role=\"button\">\r\n");
      out.write("\t            <i class=\"fas fa-th-large\"></i>\r\n");
      out.write("\t          </a>\r\n");
      out.write("\t        </li>\r\n");
      out.write("\t      </ul>\r\n");
      out.write("\t    </nav>\r\n");
      out.write("    <!-- /.navbar -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t    <!-- Main Sidebar Container -->\r\n");
      out.write("\t    ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<aside class=\"main-sidebar sidebar-dark-primary elevation-4\">\r\n");
      out.write("\t      <!-- Brand Logo -->\r\n");
      out.write("\t      <a href=\"index3.html\" class=\"brand-link\">\r\n");
      out.write("\t        <img src=\"/template/dist/img/AdminLTELogo.png\" alt=\"AdminLTE Logo\" class=\"brand-image img-circle elevation-3\"\r\n");
      out.write("\t          style=\"opacity: .8\">\r\n");
      out.write("\t        <span class=\"brand-text font-weight-light\">AdminLTE 3</span>\r\n");
      out.write("\t      </a>\r\n");
      out.write("\t\r\n");
      out.write("\t      <!-- Sidebar -->\r\n");
      out.write("\t      <div class=\"sidebar\">\r\n");
      out.write("\t        <!-- Sidebar user panel (optional) -->\r\n");
      out.write("\t        <div class=\"user-panel mt-3 pb-3 mb-3 d-flex\">\r\n");
      out.write("\t          <div class=\"image\">\r\n");
      out.write("\t            <img src=\"/template/dist/img/user2-160x160.jpg\" class=\"img-circle elevation-2\" alt=\"User Image\">\r\n");
      out.write("\t          </div>\r\n");
      out.write("\t          <div class=\"info\">\r\n");
      out.write("\t            <a href=\"#\" class=\"d-block\">Alexander Pierce</a>\r\n");
      out.write("\t          </div>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t\r\n");
      out.write("\t        <!-- SidebarSearch Form -->\r\n");
      out.write("\t        <div class=\"form-inline\">\r\n");
      out.write("\t          <div class=\"input-group\" data-widget=\"sidebar-search\">\r\n");
      out.write("\t            <input class=\"form-control form-control-sidebar\" type=\"search\" placeholder=\"Search\" aria-label=\"Search\">\r\n");
      out.write("\t            <div class=\"input-group-append\">\r\n");
      out.write("\t              <button class=\"btn btn-sidebar\">\r\n");
      out.write("\t                <i class=\"fas fa-search fa-fw\"></i>\r\n");
      out.write("\t              </button>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t          </div>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t\r\n");
      out.write("\t        <!-- Sidebar Menu -->\r\n");
      out.write("\t        <nav class=\"mt-2\">\r\n");
      out.write("\t          <ul class=\"nav nav-pills nav-sidebar flex-column\" data-widget=\"treeview\" role=\"menu\" data-accordion=\"false\">\r\n");
      out.write("\t            <li class=\"nav-item menu-open\">\r\n");
      out.write("\t              <a href=\"/home-admin\" class=\"nav-link active\">\r\n");
      out.write("\t                <i class=\"nav-icon fas fa-tachometer-alt\"></i>\r\n");
      out.write("\t                <p>\r\n");
      out.write("\t                  Dashboard\r\n");
      out.write("\t                </p>\r\n");
      out.write("\t              </a>\r\n");
      out.write("\t            </li>\r\n");
      out.write("\t            <li class=\"nav-item\">\r\n");
      out.write("\t              <a href=\"/books\" class=\"nav-link\">\r\n");
      out.write("\t                <i class=\"nav-icon fas fa-th\"></i>\r\n");
      out.write("\t                <p>\r\n");
      out.write("\t                  Quản lí sách\r\n");
      out.write("\t                  <span class=\"right badge badge-danger\">New</span>\r\n");
      out.write("\t                </p>\r\n");
      out.write("\t              </a>\r\n");
      out.write("\t            </li>\r\n");
      out.write("\t          </ul>\r\n");
      out.write("\t        </nav>\r\n");
      out.write("\t        <!-- /.sidebar-menu -->\r\n");
      out.write("\t      </div>\r\n");
      out.write("\t      <!-- /.sidebar -->\r\n");
      out.write("\t    </aside>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t    <div class=\"content-wrapper\">\r\n");
      out.write("\t      <!-- Content Header (Page header) -->\r\n");
      out.write("\t      <div class=\"content-header\">\r\n");
      out.write("\t        <div class=\"container-fluid\">\r\n");
      out.write("\t          <div class=\"row mb-2\">\r\n");
      out.write("\t            <div class=\"col-sm-6\">\r\n");
      out.write("\t              <h1 class=\"m-0 text-dark\">Danh sách tài liệu</h1>\r\n");
      out.write("\t            </div><!-- /.col -->\r\n");
      out.write("\t            <div class=\"col-sm-6\">\r\n");
      out.write("\t              <ol class=\"breadcrumb float-sm-right\">\r\n");
      out.write("\t                <li class=\"breadcrumb-item\"><a href=\"#\">pk</a></li>\r\n");
      out.write("\t              </ol>\r\n");
      out.write("\t            </div><!-- /.col -->\r\n");
      out.write("\t          </div><!-- /.row -->\r\n");
      out.write("\t        </div><!-- /.container-fluid -->\r\n");
      out.write("\t      </div>\r\n");
      out.write("\t      \r\n");
      out.write("\t      <div class=\"card\">\r\n");
      out.write("              <div class=\"card-header\">\r\n");
      out.write("                <h3 class=\"card-title\"></h3>\r\n");
      out.write("              </div>\r\n");
      out.write("              <!-- /.card-header -->\r\n");
      out.write("              <div class=\"card-body\">\r\n");
      out.write("                <table id=\"example1\" class=\"table table-bordered table-striped\">\r\n");
      out.write("                  <thead>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <th>Mã tài liệu</th>\r\n");
      out.write("                    <th>Tên tài liệu</th>\r\n");
      out.write("                    <th>Nhà xuất bản</th>\r\n");
      out.write("                    <th>Hình ảnh</th>\r\n");
      out.write("                    <th>Số lượng</th>                  \r\n");
      out.write("                    <th>Hành động</th>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  </thead>\r\n");
      out.write("                  <tbody>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td>Trident</td>\r\n");
      out.write("                    <td>Internet\r\n");
      out.write("                      Explorer 4.0\r\n");
      out.write("                    </td>\r\n");
      out.write("                    <td>Win 95+</td>\r\n");
      out.write("                    <td> 4</td>\r\n");
      out.write("                    <td>X</td>\r\n");
      out.write("                    <td>\r\n");
      out.write("                    \t<a href=\"#\">Sửa</a>\r\n");
      out.write("                    \r\n");
      out.write("                    \t<a href=\"#\">Xóa</a>\r\n");
      out.write("                    </td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  </tbody>\r\n");
      out.write("                </table>\r\n");
      out.write("              </div>\r\n");
      out.write("              <!-- /.card-body -->\r\n");
      out.write("            </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("  <!-- jQuery -->\r\n");
      out.write("  <script src=\"/template/plugins/jquery/jquery.min.js\"></script>\r\n");
      out.write("  <!-- jQuery UI 1.11.4 -->\r\n");
      out.write("  <script src=\"/template/plugins/jquery-ui/jquery-ui.min.js\"></script>\r\n");
      out.write("  <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->\r\n");
      out.write("  \r\n");
      out.write("  </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
